sudo: false
language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"
script: npm test
branches:
  only:
    - master
    - /^v[0-9]/
deploy:
  provider: npm
  email: 'public@erikdesjardins.io'
  api_key:
    secure: Q+oRXgfcpV6i6Kp+mdXpAmBEpXoILJh8ld2GczCuFh2gqmhT1aNhip4/5h1qWJ7UVhrYBlBk+7faKY5BUG5giewQst7mRqx/BXA4LwicKu9Huz2OJRrwcUjAab9ToMF9+kSDcVR1LG9Rbmi6vCF+qGgFc9cmLfxX2NNAaTF+GTwDJWjDqgxkCS3BEUL4Fmy6SlZ9VCpOBpleYwP2UwlVzfDccXl6eVmdsw9YtaQKsD//JkfR9XRjh5WeJhz6hTOVLMu+1DpnJ9GfRfo+0QFzrehNtlaiOWJSsVb5KIn4Ee7+qePmMBACOJ10IALBIkSB12lQSdFgg8XPr1ByGJehD3HREAMBEDaHXZsQJewovRxdWLe1L9gyBGJpDMJmJftpzSkrj1KNjgwZWDLv7BSwvoLliI86UGd0owkF8aT5GDDbBqNEvBrLLBEs8G+ka4AQSNvf6NNq7zP3FUgq6DSFsRpJO1cnjXrq9w0XVT8f0shKdePI/hDeExwAt+ZnnYbKF0ORBCKPpOgNxV76SdZNjzuypKz5drC8Q3bLMYeA5x8/vNtuU5Btim9yIomGqoQx2lxyGvMKyZAFj7nGkBft9HpM0ZCgz+OxQ3uQjhau4NbXHU73szSrGAEzcOQCWgsVosWdeZGNhuWmq8VoKv+YnLkFr8y/Ij9bYPRbFVjjgBQ=
  on:
    tags: true
    node: 5
